# Coveralls Configuration
# https://docs.coveralls.io/configuration

service_name: github-actions
repo_token: ${COVERALLS_REPO_TOKEN}

# Coverage file paths
coverage_clover: coverage/clover.xml
json_path: coverage/coverage-final.json

# Source files
src_dir: src

# Parallel build support (for matrix builds)
parallel: true
