name: Publish preview update

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  publish_preview:
    name: Publish preview update
    type: update
    params:
      branch: ${{ github.ref_name || 'preview' }}
